sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libgmp-dev

env:
  - STACK_YAML=stack.yaml

before_install:
  # install LXC
  - sudo apt-get install -y software-properties-common python-software-properties
  - sudo add-apt-repository -y ppa:ubuntu-lxc/stable
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" lxc-dev
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --version

install:
  - stack setup

script:
  - stack --no-terminal build --test

cache:
  directories:
    - $HOME/.stack
